name: deploy-dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js "16.x"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: 'npm'
      - run: bash scripts/create_rankpage.sh
      - run: bash scripts/switchurl.sh
      - run: npm ci
      - run: npm run build
      - run: npm test -- --coverage --watchAll=false
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-dev
          publish_dir: ./build
